kind: Endpoints
apiVersion: v1
metadata:
  name: low-code-mongodb-svc
  namespace: ddo
subsets:
  - addresses:
      - ip: 192.168.3.91
    ports:
      - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: low-code-mongodb-svc
  namespace: ddo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
