kind: Endpoints
apiVersion: v1
metadata:
  name: low-code-mysql-svc
  namespace: bpmn
subsets:
  - addresses:
      - ip: 192.168.3.47
    ports:
      - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: low-code-mysql-svc
  namespace: bpmn
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306