apiVersion: v1
kind: Service
metadata:
  name: low-code-svc
  namespace: tianshu
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 32187
  selector:
    app: low-code
